# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Innovation Lab Brand Guidelines
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Innovation Lab Brand Guidelines
baseurl: "/innovation-lab-brand-guidelines" # the subpath of your site, e.g. /blog
url: "http://vizzuality.github.io/" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
permalink: none
paginate: 1

# Build settings
markdown: kramdown
